### PR TITLE
Braille

### PR DESCRIPTION
**Pull request by konsumer**
Adds example program to output nice braille mazes:

```
lua source/braille.lua 20 20 recursive_backtracker

⣏⣉⠉⠉⠉⢹⡏⠉⣉⣉⠉⢹⡏⠉⠉⢹⡏⢹⡏⠉⠉⠉⣉⣉⣉⣉⣉⣉⠉⢹⣏⣉⣉⣉⠉⠉⣉⣉⠉⢹
⡏⠉⣀⣸⡇⢸⡇⢸⡏⢹⣇⣀⣀⣸⡇⢸⣇⣀⣀⣸⣇⣀⣉⣉⠉⢹⣏⣉⣀⣀⣉⣉⣉⣉⣀⣸⡏⠉⣀⣸
⡇⢸⣏⣉⣀⣀⣀⣸⡇⠀⣉⣹⡏⠉⣀⣸⡏⠉⣉⣉⣉⣉⠉⢹⣇⣀⠉⢹⡏⠉⣉⣉⣉⣉⠉⢹⣇⣀⠉⢹
⣇⣀⠉⠉⠉⢹⡏⠉⣀⣸⡏⠉⣀⣸⣏⣉⣀⣀⠉⢹⡏⢹⡇⢸⡏⠉⣀⣸⡇⢸⡏⠉⠉⢹⣇⣀⣉⣉⣀⣸
⡏⢹⣇⣸⡇⢸⡇⢸⡏⠉⣀⣸⡏⠉⣉⣉⣉⣉⣀⣸⣇⣀⣀⣀⣀⣸⡏⠉⣀⣸⡇⢸⣇⣀⣉⣉⣉⣉⠉⢹
⣇⣀⣉⣉⣀⣸⡇⢸⡇⢸⡏⠉⣀⣀⣉⣉⣉⣉⣉⣉⠉⢹⡏⠉⠉⢹⣇⣀⠉⢹⡇⢸⡏⠉⣉⣉⣉⣉⣀⣸
⡏⠉⠉⠉⣉⣉⣀⣸⡇⢸⡇⢸⡏⠉⣉⣉⠉⢹⡏⠉⣀⣸⣇⣸⡇⠀⠉⢹⡇⢸⡇⢸⣇⣀⣉⣉⣉⣉⠉⢹
⡇⢸⡇⢸⡏⠉⣉⣉⣀⣸⣇⣀⣀⣸⣏⣉⣀⣸⡇⢸⡏⠉⠉⢹⡇⢸⣇⣀⣀⣸⣇⣸⡏⠉⣉⣉⠉⢹⡇⢸
⡇⢸⡇⢸⣇⣀⠉⢹⡏⠉⣉⣉⣉⣉⣉⣉⠉⢹⣇⣀⣀⣸⡇⢸⣇⣀⣉⣉⣉⣉⣉⣉⣀⣸⡏⢹⣇⣀⠀⢸
⡇⢸⡇⠀⠉⢹⣇⣀⣀⣸⣏⣉⠉⠉⠉⢹⣇⣀⠉⢹⡏⠉⣀⣸⡏⠉⠉⠉⣉⣉⠉⢹⡏⠉⠀⢸⡏⢹⡇⢸
⣇⣸⡇⢸⣇⣀⣉⣉⠉⠉⣉⣉⣀⣸⣇⣀⣉⣹⡇⢸⣇⣀⠉⢹⣇⣸⡇⠀⠉⢹⣇⣀⣀⣸⡇⠀⣀⣸⡇⢸
⡏⠉⠀⢸⡏⠉⠉⢹⣇⣸⡏⠉⣉⣉⣉⣉⠉⢹⣇⣀⠉⢹⡇⠀⠉⢹⡇⢸⡇⢸⡏⠉⠉⢹⡇⢸⡏⠉⣀⣸
⡇⢸⣇⣸⡇⢸⣇⣀⠉⢹⡇⢸⡏⠉⠉⢹⣇⣀⣉⣉⣀⣸⡇⢸⡇⢸⣇⣸⡇⢸⡇⢸⣇⣸⡇⢸⡇⢸⡏⢹
⣇⣀⠉⢹⡇⢸⡏⢹⣇⣀⣀⣸⣇⣸⣇⣀⣉⣉⣉⣉⣉⣉⣀⣸⡇⠀⠉⢹⡇⢸⣇⣀⣉⣉⣀⣸⣇⣀⠀⢸
⡏⠉⠀⢸⡇⢸⡇⠀⣉⣉⣉⣉⣉⣉⣉⣉⣉⣉⣉⣉⣉⣉⠉⢹⡇⢸⡇⢸⡇⠀⣉⣉⠉⢹⡏⠉⣉⣉⣀⣸
⡇⢸⣇⣸⣇⣀⣀⣸⡏⠉⣉⣉⣉⣉⠉⢹⡏⢹⡏⠉⣉⣉⣀⣸⣇⣸⡇⢸⡇⢸⡏⠉⠀⢸⣇⣀⠉⢹⡏⢹
⣇⣀⣉⣉⠉⢹⡏⠉⣀⣀⣉⣉⠉⢹⣇⣀⣀⣸⡇⢸⡏⠉⣉⣉⣉⣉⣀⣸⣇⣸⡇⢸⣇⣸⡏⠉⣀⣸⡇⢸
⡏⠉⣉⣉⣀⣸⣇⣀⣉⣉⠉⢹⣇⣀⠉⢹⡏⠉⣀⣸⡇⢸⡏⠉⣉⣉⣉⣉⣉⣉⠀⢸⡏⠉⣀⣸⡏⠉⠀⢸
⡇⠀⣉⣉⣉⣉⠉⠉⣉⣹⡇⢸⡏⠉⣀⣸⣇⣀⣉⣉⣀⣸⡇⢸⡏⠉⠉⢹⣏⣉⣀⣸⣇⣀⠉⢹⣇⣸⡇⢸
⣇⣀⣉⣉⣉⣹⣇⣀⣉⣉⣀⣸⣇⣀⣉⣉⣉⣉⣉⣉⣉⣉⣀⣀⣀⣸⣇⣀⣉⣉⣉⣉⣉⣉⣀⣀⣉⣉⣀⣸
```
Requires lua 5.3. Related to #4

### CODE REVIEW

**Comment by konsumer** [comment]
I included the other PR by accident, so if you like both ideas, I think you can just merge this one.

**Comment by konsumer** [comment]
Another sidenote, love adds `utf8` via `utf8 = require "utf8"` as does luarocks "utf8" so it's not just lua 5.3:

Screenshot from 2021-03-17 21-59-37

**Comment by shironecko** [comment]
Hey! Love this idea, braille certainly look a lot cleaner that just printing hashtags and spaces.
Although I have already merged your other PR so Git get's confused with the commits that are already in my master. Serves me right for rushing to merge without looking at all of the PRs 😅 
Can you update this PR by merging my master into you braille branch to make the diff cleaner?

**Comment by konsumer** [comment]
No prob!

**Comment by konsumer** [comment]
Ok, added better one: #7 going to close this.

**Pull request closed without merging**
